name: Build and Deploy nbdev Documentation
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1

      - name: Install and Build ğŸ”§ # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          pip install nbdev==1.2.2
          pip install -e .
          sudo apt-get install subversion
      - name: Clone the template repository files including Gemfile and other needed bits
        run: |
          svn export https://github.com/muellerzr/nbdev_doc_automation/trunk/docs --force 
      - name: Build documentation
        run: |
          nbdev_build_docs
          
      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs # The folder the action should deploy.